import React from 'react';
import { Brain, Target, BarChart3, MessageCircle, BookOpen, Shield, LucideIcon } from 'lucide-react';

interface Feature {
  icon: LucideIcon;
  title: string;
  desc: string;
  color: string;
  bg: string;
}

const features: Feature[] = [
  { icon: Brain, title: 'AI Tutor', desc: 'Get instant answers to any question. Our AI tutor explains concepts clearly and generates practice questions.', color: 'text-blue-500', bg: 'bg-blue-50' },
  { icon: Target, title: 'Practice Mode', desc: 'Short, focused practice sessions on specific topics. Build confidence one question at a time.', color: 'text-green-500', bg: 'bg-green-50' },
  { icon: BookOpen, title: 'Mock Exams', desc: 'Full-length mock exams auto-generated by AI from our question bank covering S1-S3 material.', color: 'text-purple-500', bg: 'bg-purple-50' },
  { icon: BarChart3, title: 'Progress Tracking', desc: 'See your scores, track improvement over time, and identify weak areas to focus on.', color: 'text-amber-500', bg: 'bg-amber-50' },
  { icon: MessageCircle, title: 'Community', desc: 'Join a community of learners. Post questions, get answers from peers and teachers.', color: 'text-rose-500', bg: 'bg-rose-50' },
  { icon: Shield, title: 'Real Exam Questions', desc: 'Practice with actual national exam questions from 2018-2025 plus textbook questions.', color: 'text-teal-500', bg: 'bg-teal-50' },
];

export default function FeaturesSection() {
  return (
    <section className="py-20 bg-white">
      <div className="max-w-7xl mx-auto px-4">
        <div className="text-center mb-14">
          <div className="flex items-center gap-2 justify-center mb-4">
            <div className="w-2 h-2 bg-primary rounded-full" />
            <span className="text-primary font-semibold text-sm uppercase tracking-wider">Platform Features</span>
          </div>
          <h2 className="font-heading font-extrabold text-3xl md:text-4xl text-foreground">
            Everything You Need to Succeed
          </h2>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((f: Feature, i: number) => (
            <div key={i} className="group p-8 rounded-3xl border border-border hover:border-primary/20 bg-white hover:shadow-xl transition-all duration-300">
              <div className={`w-16 h-16 ${f.bg} rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform`}>
                <f.icon className={`w-8 h-8 ${f.color}`} />
              </div>
              <h3 className="font-heading font-bold text-lg text-foreground mb-3">{f.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}