import React, { useState } from 'react';
import { Brain, Target, BarChart3, MessageCircle, BookOpen, Shield, LucideIcon } from 'lucide-react';

interface Feature {
  icon: LucideIcon;
  title: string;
  desc: string;
  color: string;
  bg: string;
  borderColor: string;
  hoverBg: string;
  stats: string;
}

const features: Feature[] = [
  { 
    icon: Brain, 
    title: 'AI Tutor', 
    desc: 'Get instant answers to any question. Our AI tutor explains concepts clearly and generates practice questions tailored to your needs.',
    color: 'text-blue-500', 
    bg: 'bg-blue-50',
    borderColor: 'hover:border-blue-200',
    hoverBg: 'hover:bg-blue-50/50',
    stats: '24/7 Available'
  },
  { 
    icon: Target, 
    title: 'Practice Mode', 
    desc: 'Short, focused practice sessions on specific topics. Build confidence one question at a time with instant feedback.',
    color: 'text-green-500', 
    bg: 'bg-green-50',
    borderColor: 'hover:border-green-200',
    hoverBg: 'hover:bg-green-50/50',
    stats: '5,000+ Questions'
  },
  { 
    icon: BookOpen, 
    title: 'Mock Exams', 
    desc: 'Full-length mock exams auto-generated by AI from our question bank covering S1-S3 material with real exam simulation.',
    color: 'text-purple-500', 
    bg: 'bg-purple-50',
    borderColor: 'hover:border-purple-200',
    hoverBg: 'hover:bg-purple-50/50',
    stats: '20+ Mock Tests'
  },
  { 
    icon: BarChart3, 
    title: 'Progress Tracking', 
    desc: 'See your scores, track improvement over time, and identify weak areas to focus on with detailed analytics.',
    color: 'text-amber-500', 
    bg: 'bg-amber-50',
    borderColor: 'hover:border-amber-200',
    hoverBg: 'hover:bg-amber-50/50',
    stats: 'Detailed Analytics'
  },
  { 
    icon: MessageCircle, 
    title: 'Community', 
    desc: 'Join a community of learners. Post questions, get answers from peers and teachers, and learn together.',
    color: 'text-rose-500', 
    bg: 'bg-rose-50',
    borderColor: 'hover:border-rose-200',
    hoverBg: 'hover:bg-rose-50/50',
    stats: '1,500+ Members'
  },
  { 
    icon: Shield, 
    title: 'Real Exam Questions', 
    desc: 'Practice with actual national exam questions from 2018-2025 plus textbook questions verified by teachers.',
    color: 'text-teal-500', 
    bg: 'bg-teal-50',
    borderColor: 'hover:border-teal-200',
    hoverBg: 'hover:bg-teal-50/50',
    stats: '7 Years Coverage'
  },
];

export default function FeaturesSection() {
  const [activeFeature, setActiveFeature] = useState(null);
  const [hoveredFeature, setHoveredFeature] = useState(null);

  return (
    <section className="py-20 bg-white relative overflow-hidden">
      {/* Background Pattern */}
      <div className="absolute inset-0 bg-[linear-gradient(rgba(0,0,0,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(0,0,0,0.02)_1px,transparent_1px)] bg-[size:48px_48px]" />
      
      <div className="max-w-7xl mx-auto px-4 relative z-10">
        {/* Header with animation */}
        <div className="text-center mb-14 animate-fadeInUp">
          <div className="flex items-center gap-2 justify-center mb-4">
            <div className="w-2 h-2 bg-primary rounded-full animate-pulse" />
            <span className="text-primary font-semibold text-sm uppercase tracking-wider">Platform Features</span>
          </div>
          <h2 className="font-heading font-extrabold text-3xl md:text-4xl text-foreground mb-4">
            Everything You Need to Succeed
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Our platform combines powerful tools to help you prepare effectively for your national exams
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <div 
              key={index} 
              className={`group relative bg-card rounded-sm border border-border transition-all duration-300 cursor-pointer
                ${feature.borderColor}
                ${activeFeature === index ? 'ring-2 ring-primary shadow-xl scale-105' : 'hover:shadow-lg hover:scale-105'}
                animate-fadeInUp`}
              style={{ animationDelay: `${index * 100}ms` }}
              onClick={() => setActiveFeature(activeFeature === index ? null : index)}
              onMouseEnter={() => setHoveredFeature(index)}
              onMouseLeave={() => setHoveredFeature(null)}
            >
              {/* Feature Card Content */}
              <div className="p-6">
                {/* Icon Container */}
                <div className="flex items-start justify-between mb-4">
                  <div className={`w-14 h-14 ${feature.bg} rounded-sm flex items-center justify-center transition-transform duration-300
                    ${hoveredFeature === index || activeFeature === index ? 'scale-110 rotate-3' : 'group-hover:scale-110'}`}>
                    <feature.icon className={`w-7 h-7 ${feature.color} transition-transform duration-300
                      ${hoveredFeature === index || activeFeature === index ? 'scale-110' : ''}`} 
                    />
                  </div>
                  
                  {/* Stat Badge */}
                  <div className={`px-3 py-1 rounded-sm text-xs font-semibold border transition-all duration-300
                    ${hoveredFeature === index || activeFeature === index 
                      ? 'bg-primary text-primary-foreground border-primary' 
                      : 'bg-muted text-muted-foreground border-border'
                    }`}>
                    {feature.stats}
                  </div>
                </div>

                {/* Title */}
                <h3 className="font-heading font-bold text-lg text-foreground mb-2 transition-colors duration-300
                  ${activeFeature === index ? 'text-primary' : ''}">
                  {feature.title}
                </h3>

                {/* Description */}
                <p className="text-sm text-muted-foreground leading-relaxed mb-4">
                  {feature.desc}
                </p>

                {/* Interactive Elements - Show on hover/active */}
                <div className={`transition-all duration-300 overflow-hidden
                  ${hoveredFeature === index || activeFeature === index ? 'max-h-20 opacity-100' : 'max-h-0 opacity-0'}`}>
                  <div className="pt-3 border-t border-border">
                    <div className="flex items-center justify-between">
                      <span className="text-xs text-muted-foreground">
                        {activeFeature === index ? 'Click to close' : 'Click to learn more'}
                      </span>
                      <div className={`w-6 h-6 rounded-sm flex items-center justify-center transition-all duration-300
                        ${activeFeature === index ? 'bg-primary text-primary-foreground rotate-180' : 'bg-muted text-muted-foreground'}`}>
                        ↓
                      </div>
                    </div>
                  </div>
                </div>

                {/* Active Indicator */}
                {activeFeature === index && (
                  <div className="absolute top-3 right-3">
                    <div className="w-2 h-2 bg-primary rounded-sm animate-pulse" />
                  </div>
                )}
              </div>

              {/* Expanded Content */}
              {activeFeature === index && (
                <div className="px-6 pb-6 animate-scaleIn">
                  <div className={`p-4 rounded-sm ${feature.bg} ${feature.color}`}>
                    <p className="text-sm font-medium">
                      {feature.title === 'AI Tutor' && 'Ask questions anytime, get step-by-step explanations, and receive personalized practice recommendations.'}
                      {feature.title === 'Practice Mode' && 'Choose specific topics, set your pace, and get instant feedback with detailed explanations for each answer.'}
                      {feature.title === 'Mock Exams' && 'Experience real exam conditions with timed tests, instant scoring, and detailed performance analysis.'}
                      {feature.title === 'Progress Tracking' && 'Visual dashboards showing your strengths, areas for improvement, and study time analytics.'}
                      {feature.title === 'Community' && 'Connect with fellow students, share study tips, and get help from experienced teachers.'}
                      {feature.title === 'Real Exam Questions' && 'Access verified past papers and practice materials aligned with the national curriculum.'}
                    </p>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="text-center mt-12 animate-fadeInUp" style={{ animationDelay: '600ms' }}>
          <p className="text-muted-foreground mb-4">
            Ready to explore all features?
          </p>
          <button 
            onClick={() => setActiveFeature(null)}
            className="text-primary font-semibold hover:underline"
          >
            Reset selection ↑
          </button>
        </div>
      </div>

      {/* CSS Animations */}
      <style>{`
        @keyframes fadeInUp {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        
        @keyframes scaleIn {
          from {
            opacity: 0;
            transform: scaleY(0);
            max-height: 0;
          }
          to {
            opacity: 1;
            transform: scaleY(1);
            max-height: 200px;
          }
        }
        
        .animate-fadeInUp {
          animation: fadeInUp 0.6s ease-out forwards;
          opacity: 0;
        }
        
        .animate-scaleIn {
          animation: scaleIn 0.3s ease-out forwards;
          transform-origin: top;
        }
      `}</style>
    </section>
  );
}